export const GET_ALL_PACIENTS = "GET_ALL_PACIENTS"
export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS"
export const GET_CLINICAL_HISTORY = "GET_CLINICAL_HISTORY"
export const GET_ALL_ATENTIONS = "GET_ALL_ATENTIONS"

export const ADD_PACIENT = "ADD_PACIENT"
export const ADD_DOCTOR = "ADD_DOCTOR"
export const ADD_CLINICAL_HISTORY = "ADD_CLINICAL_HISTORY"
export const ADD_ATENTIONS = "ADD_ATENTIONS"