export const GET_ALL_PACIENTS = "GET_ALL_PACIENTS";
export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS";
export const GET_CLINICAL_HISTORY = "GET_CLINICAL_HISTORY";
export const GET_ALL_ATENTIONS = "GET_ALL_ATENTIONS";

export const ADD_PACIENT = "ADD_PACIENT";
export const ADD_DOCTOR = "ADD_DOCTOR";
export const ADD_CLINICAL_HISTORY = "ADD_CLINICAL_HISTORY";
export const ADD_ATENTIONS = "ADD_ATENTIONS";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_AVAILABLE_DOCTOR = "GET_AVAILABLE_DOCTOR";
export const CREATE_ATTENTION = "CREATE_ATTENTION";
export const GET_ENCURSO_ATTENTION = "GET_ENCURSO_ATTENTION";
