export const GET_ALL_PACIENTS = "GET_ALL_PACIENTS";
export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS";
export const GET_CLINICAL_HISTORY = "GET_CLINICAL_HISTORY";
export const GET_ALL_ATENTIONS = "GET_ALL_ATENTIONS";

export const GET_ALL_PAGOS = "GET_ALL_PAGOS";
export const PUT_PAGO_STATUS = "PUT_PAGO_STATUS";

export const GET_USER_BY_NUM_DOCUMENT = "GET_USER_BY_NUM_DOCUMENT";

export const ADD_PACIENT = "ADD_PACIENT";
export const ADD_DOCTOR = "ADD_DOCTOR";
export const ADD_CLINICAL_HISTORY = "ADD_CLINICAL_HISTORY";
export const ADD_ATENTIONS = "ADD_ATENTIONS";

export const PUT_PACIENT = "PUT_PACIENT";
export const PUT_DOCTOR = "PUT_DOCTOR";
export const PUT_CLINICAL_HISTORY = "PUT_CLINICAL_HISTORY";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_AVAILABLE_DOCTOR = "GET_AVAILABLE_DOCTOR";
export const CREATE_ATTENTION = "CREATE_ATTENTION";
export const GET_ATTENTION = "GET_ATTENTION";
export const GET_TOTAL_USERS = "GET_TOTAL_USERS";

export const ADD_ANTECEDENTE = "ADD_ANTECEDENTE";

export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const PACIENT_ACTIVATE_DESACTIVATE = "PACIENT_ACTIVATE_DESACTIVATE";
export const DOCTOR_ACTIVATE_DESACTIVATE = "DOCTOR_ACTIVATE_DESACTIVATE";

export const GMAIL_PACIENT = "GMAIL_PACIENT"

